# Generated by Django 2.2.24 on 2023-04-28 08:59

from django.db import migrations


def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_auto_20230428_1825'),
    ]

    operations = [
        migrations.RunPython(is_new_building)
    ]
