# Generated by Django 2.2.24 on 2023-04-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_add_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='address',
        ),
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.ManyToManyField(to='property.Flat', verbose_name='Адрес квартиры'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
