# Generated by Django 2.2.24 on 2023-04-30 13:50

from django.db import migrations
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber


def owner_pure_phone(apps, schema_editor):
    class PhoneForm(forms.Form):
        number = PhoneNumberField(region="RU")

    flats = apps.get_model('property', 'Flat')
    flats = flats.objects.all()

    for flat in flats:
        owners_phonenumber = flat.owners_phonenumber
        form = PhoneForm({"number": owners_phonenumber})
        if form.is_valid():
            number = PhoneNumber.from_string(owners_phonenumber, 'RU')
            flat.owner_pure_phone = number
            flat.save()
        else:
            flat.owner_pure_phone = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_phone_number_field'),
    ]

    operations = [
        migrations.RunPython(owner_pure_phone)
    ]
