# Generated by Django 2.2.24 on 2023-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_to_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='addresses',
            field=models.ManyToManyField(related_name='apartment_owners', to='property.Flat', verbose_name='Квартиры владельца'),
        ),
    ]
