# Generated by Django 2.2.24 on 2023-05-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_fix_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
