# Generated by Django 2.2.24 on 2023-05-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_flat_clean_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='addresses',
        ),
        migrations.AddField(
            model_name='complaint',
            name='apartments',
            field=models.ManyToManyField(related_name='apartment_complaints', to='property.Flat', verbose_name='Адрес квартиры'),
        ),
        migrations.AddField(
            model_name='owner',
            name='apartments',
            field=models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры владельца'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
