# Generated by Django 2.2.24 on 2023-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_related_names_fix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='apartments',
            field=models.ManyToManyField(related_name='complaints', to='property.Flat', verbose_name='Адрес квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда создано объявление'),
        ),
    ]
